// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA65Nn-PW8wL4ytWr0RPVCZXmZScdAaZY',
    appId: '1:79151566841:web:44b4dfeaca298323ab7728',
    messagingSenderId: '79151566841',
    projectId: 'ahmed123-e7751',
    authDomain: 'ahmed123-e7751.firebaseapp.com',
    storageBucket: 'ahmed123-e7751.firebasestorage.app',
    measurementId: 'G-8RQSB74J5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwZfZodSls4_DV5Tw9ODQN54GR29I73c',
    appId: '1:79151566841:android:bcad4a8b090acd09ab7728',
    messagingSenderId: '79151566841',
    projectId: 'ahmed123-e7751',
    storageBucket: 'ahmed123-e7751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2F5xdBminiqSX7dJ1lqM7dr4ke9KJsHs',
    appId: '1:79151566841:ios:d1936843ead04c37ab7728',
    messagingSenderId: '79151566841',
    projectId: 'ahmed123-e7751',
    storageBucket: 'ahmed123-e7751.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2F5xdBminiqSX7dJ1lqM7dr4ke9KJsHs',
    appId: '1:79151566841:ios:d1936843ead04c37ab7728',
    messagingSenderId: '79151566841',
    projectId: 'ahmed123-e7751',
    storageBucket: 'ahmed123-e7751.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA65Nn-PW8wL4ytWr0RPVCZXmZScdAaZY',
    appId: '1:79151566841:web:b06ab61e74766e58ab7728',
    messagingSenderId: '79151566841',
    projectId: 'ahmed123-e7751',
    authDomain: 'ahmed123-e7751.firebaseapp.com',
    storageBucket: 'ahmed123-e7751.firebasestorage.app',
    measurementId: 'G-ETQZCMZ06W',
  );
}
